/********************************************************************
 * Kyle Lee
 * Instructor.cpp
 * May 6, 2015
 * CSE 202 (Wednesday lab)
 * Description: Write functions to modify and print Instructor 
   member variables (including salary).
 * Solution: Use functions from base class Person, and expand on
   these functions by adding functionality (setting the salary, etc.).
 * Percent complete: 100%
********************************************************************/

#include <string>
#include <iostream>

#include "Instructor.h"

using namespace std;

//Default constructor
Instructor::Instructor(): Person(), salary(0) { }
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000883 begin


// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000883 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

//Constructor that initializes name, DOB, gender, and salary
Instructor::Instructor(string n, string d, string g, int s): Person(n, d, g), salary(s) { }
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000885 begin


// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000885 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

//Prints instructor name and salary
void Instructor::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000895 begin
{
    if (gender == "M")
        cout << "Mr. ";
    else
        cout << "Ms. ";
	Person::print();
	cout << "    Instructor, Salary: " << salary << endl;
}
// section -117--74--108--126-566dc4d1:14d2b87c0eb:-8000:0000000000000895 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
